name: Build Docker Builder Factory

on:
  push:
    branches:
      - master
    paths:
      - 'builder.Dockerfile'
      - '**docker-builder.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'builder.Dockerfile'
      - '**docker-builder.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2

    - name: Set outputs
      id: vars
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./builder.Dockerfile
        push: true
        tags: |
          ${{ github.repository_owner }}/builder:latest
          ${{ github.repository_owner }}/builder:${{ steps.vars.outputs.sha_short }}
          ghcr.io/${{ github.repository_owner }}/builder:latest
          ghcr.io/${{ github.repository_owner }}/builder:${{ steps.vars.outputs.sha_short }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
